# Generated by Django 4.1.7 on 2023-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=255)),
                ('Orden', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=9)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=50)),
                ('Cantidad', models.FloatField(max_length=100)),
                ('IBAN', models.CharField(max_length=24)),
                ('Beneficiario', models.CharField(max_length=100)),
                ('Concepto', models.CharField(max_length=100)),
                ('Bank', models.CharField(max_length=100)),
                ('BIC', models.CharField(max_length=50))
            ],
        ),
    ]
